import { Link } from "react-router-dom";

export default function UnemploymentInsurance(props) {

    return (
        <div>
            <h2>Unemployment Insurance</h2>
            <img src="../../figures/Unemployment_Insurance.png"/>
            <p>Among the many gifts to humanity inspired by the Wisconsin Idea, the development of Unemployment compensation saved the state of Wisconsin, and later the entire country.  In 1906, Professor John R. Commons created the American Association of Labor Legislation.  While the goals of this group were to provide labor laws for all of America, the Association started with state legislation to gain traction.  The first official legislation to help Wisconsin citizens came 29 years later: “Wisconsin was the first state to enact unemployment compensation benefits for its citizens, in 1932. And the Wisconsin system, designed in large measure by Professor Commons, was the starting point for the federal unemployment insurance program that became part of the Social Security Act in 1935.” (an expert of Research Note #8: The Special Role of the University of Wisconsin in the History of Social Security, From the Agency History of Social Security.)  Originally, these state laws were enacted as a way to help citizens during the Great depression.  Although these laws would soon be reformed to encompass all American citizens, the progressive law started in the walls of the University as a way to lessen the impacts of the Great Depression for Wisconsinites.  Inspired by these laws, Teddy Roosevelt hired Edwin Witte as Executive Director of the Presidential Committee on Economic Security (CES) that designed the Social Security program in the summer and fall of 1934.  Following this, several Wisconsin Alumni, including Arthur Altmeyer, and other writers of the original Unemployment Compensation bills were hired to the Social Security Board,  which was the organization created to carry out the Social Security Act. Specifically, Arthur Altmeyer a protege of John Commons can be given large amounts of credit for the existence of modern social security.</p>
            <p>While Social Security is a benefit that now affects all citizens of the United States, it started as a Wisconsin law to combat unemployment and other adverse reactions associated with the Great Depression.  Due to the success these reformations had within Wisconsin, Teddy Roosevelt hired many of the original pioneers of SS to The Committee of Economic security.  Through this many Wisconsin Alum fitted the original Wisconsin Unemployment laws into the modern Social Security program that in essence is still used today. </p>
            <p>One additional example of the Wisconsin Idea helping state residents as well as the rest of the world is found in Velicon.  This is a Wisconsin based company that has partnered with the engineering department in hopes to make an engine free of rare metals for the electric automobile industry.  Through their work with WARF, Velicon is currently providing jobs in the Milwaukee area as they strive to manufacture a cleaner electric engine.  The possibilities are significant for the University, the state of Wisconsin, and the World.  In addition to decreasing pollution from lithium powered engines, Velicon has the potential to become a worldwide employer.  As their current headquarters is in Wisconsin,  further economic growth is possible alongside the growth of the company. Velicon’s non-lithium motors are in line the environmental concern shared by Wisconsinites.</p>
        </div>
    );
}
